"""Clustering configuration: the two schemes, their knobs, and the experiment grid.

Two schemes, each parameterised by its own natural knob (paper, incl. Fig. 4):

  K  (KMeans)               -> cluster COUNT k. Produces exactly k clusters.
  D  (Dynamic/Agglomerative)-> cosine-similarity THRESHOLD. The cluster count emerges
                               from the threshold (distance = 1 - similarity) and is
                               capped at D_CAP so the judge prompt stays bounded.

Config tags: 'K2','K4','K8' (k) and 'D75','D80','D85' (threshold*100).
"""
from __future__ import annotations

# Datasets covered (NewsCLIPpings is excluded -- the paper uses its provided evidence
# with no collection/refinement, so it has no clusters here).
DATASETS = ["5PILS_OOC", "MMFakeBench_val", "dt_4k", "verite"]

# Text embedder used for clustering (local SentenceTransformer, 384-d). Cached model id.
EMBED_MODEL = "all-MiniLM-L6-v2"

# Scheme knobs.
KMEANS_KS = [2, 4, 8]               # KMeans: exact k
D_THRESHOLDS = [0.75, 0.80, 0.85]   # Dynamic: cosine-similarity thresholds (Fig. 4)
D_CAP = 8                           # threshold sets the count; never exceed this many


def thr_tag(threshold):
    """0.75 -> 75 (the integer tag used in filenames/configs)."""
    return int(round(threshold * 100))


# The 6 experiment configs as (algo, tag). K4 == the baseevd file (data/{ds}_K4_wo.json);
# the other 5 are generated by generate_clusters.
CONFIGS = (
    [("K", k) for k in KMEANS_KS]
    + [("D", thr_tag(t)) for t in D_THRESHOLDS]
)


def config_tag(algo, tag):
    """('K',2) -> 'K2', ('D',75) -> 'D75'."""
    return f"{algo}{tag}"


def cluster_params(algo, tag):
    """Map a config to the clustering call's (num_clusters_or_cap, similarity_threshold).

    K: (k, None)            -- exact k clusters.
    D: (D_CAP, threshold)   -- threshold-driven, capped at D_CAP.
    """
    if algo == "K":
        return tag, None
    if algo == "D":
        return D_CAP, tag / 100.0
    raise ValueError(f"Unknown algo {algo!r}")
